In [1]:
base_url = f"https://www.freshersworld.com/jobs/jobsearch/data-analyst-jobs-in-delhi"

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [9]:
response = requests.get(base_url)
soup = BeautifulSoup(response.text,"html.parser")
page_jobs = soup.find_all("div",{"class":"col-md-12 col-lg-12 col-xs-12 padding-none job-container jobs-on-hover top_space"})
len(page_jobs)

20

In [22]:
job_posts=[]
for i in page_jobs:
    job_list={}
    job_list["title"] = i.find("span",{"class":"wrap-title seo_title"}).text
    job_list['Company Name'] = i.find("h3",{"class":"latest-jobs-title font-16 margin-none inline-block company-name"}).text
    job_list['Time'] = i.find("div",{"class":"text-ago"}).text
    job_posts.append(job_list)
print(job_posts)

[{'title': 'Data Analyst Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 1 days ago'}, {'title': 'Data Analyst Jobs Opening in Client Of Freshersworld at DelhiLess', 'Company Name': 'Client Of Freshersworld', 'Time': 'Posted: 25 days ago'}, {'title': 'Data Analyst Jobs Opening in Client of Teamlease at DelhiLess', 'Company Name': 'Client of Teamlease', 'Time': 'Posted: 22 days ago'}, {'title': 'Data Entry Analyst Jobs Opening in IMPERIALS at Ashok Vihar, DelhiLess', 'Company Name': 'IMPERIALS', 'Time': 'Posted: 25 days ago'}, {'title': 'Data Analyst Senior Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 21 days ago'}, {'title': 'Product Data Management Analyst Jobs Opening in Client Of Freshersworld at DelhiLess', 'Company Name': 'Client Of Freshersworld', 'Time': 'Posted: 22 days ago'}, {'title': 'Data Analyst Power BI Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Data Analyst Power BI Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Finance Analyst Jobs Opening in Client of Teamlease at Delhi-Others, DelhiLess', 'Company Name': 'Client of Teamlease', 'Time': 'Posted: 1 months ago'}, {'title': 'SEO Analyst Jobs Opening in Webvio Technologies at Okhla, DelhiLess', 'Company Name': 'Webvio Technologies', 'Time': 'Posted: 1 months ago'}, {'title': 'Catalog Analyst Jobs Opening in Client of freshersworld at Delhi-Others, DelhiLess', 'Company Name': 'Client of freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Finance Analyst Jobs Opening in Client of Teamlease at Delhi-Others, DelhiLess', 'Company Name': 'Client of Teamlease', 'Time': 'Posted: 1 months ago'}, {'title': 'Business Analyst Jobs Opening in A client of freshersworld at DelhiLess', 'Company Name': 'A client of freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Catalog Analyst Jobs Opening in Client of freshersworld at Delhi-Others, DelhiLess', 'Company Name': 'Client of freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Business Analyst Jobs Opening in A client of freshersworld at DelhiLess', 'Company Name': 'A client of freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'Market Research Analyst Jobs Opening in ODN Digital Services Private Limited at DelhiLess', 'Company Name': 'ODN Digital Services Private Limited', 'Time': 'Posted: 6 days ago'}, {'title': 'Stock Market Research Analyst Jobs Opening in Private Office at Janakpuri, DelhiLess', 'Company Name': 'Private Office', 'Time': 'Posted: 1 months ago'}, {'title': 'Network Security Risk Analyst Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 9 days ago'}, {'title': 'IT Project Senior Analyst Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 1 months ago'}, {'title': 'IT Project Senior Analyst Jobs Opening in A Client of Freshersworld at DelhiLess', 'Company Name': 'A Client of Freshersworld', 'Time': 'Posted: 1 months ago'}]

In [23]:
df = pd.DataFrame(job_posts)
df

,title,Company Name,Time
0,Data Analyst Jobs Opening in A Client of Fresh...,A Client of Freshersworld,Posted: 1 days ago
1,Data Analyst Jobs Opening in Client Of Fresher...,Client Of Freshersworld,Posted: 25 days ago
2,Data Analyst Jobs Opening in Client of Teamlea...,Client of Teamlease,Posted: 22 days ago
3,Data Entry Analyst Jobs Opening in IMPERIALS a...,IMPERIALS,Posted: 25 days ago
4,Data Analyst Senior Jobs Opening in A Client o...,A Client of Freshersworld,Posted: 21 days ago
5,Product Data Management Analyst Jobs Opening i...,Client Of Freshersworld,Posted: 22 days ago
6,Data Analyst Power BI Jobs Opening in A Client...,A Client of Freshersworld,Posted: 1 months ago
7,Data Analyst Power BI Jobs Opening in A Client...,A Client of Freshersworld,Posted: 1 months ago
8,Finance Analyst Jobs Opening in Client of Team...,Client of Teamlease,Posted: 1 months ago
9,SEO Analyst Jobs Opening in Webvio Technologie...,Webvio Technologies,Posted: 1 months ago
10,Catalog Analyst Jobs Opening in Client of fres...,Client of freshersworld,Posted: 1 months ago
11,Finance Analyst Jobs Opening in Client of Team...,Client of Teamlease,Posted: 1 months ago
12,Business Analyst Jobs Opening in A client of f...,A client of freshersworld,Posted: 1 months ago
13,Catalog Analyst Jobs Opening in Client of fres...,Client of freshersworld,Posted: 1 months ago
14,Business Analyst Jobs Opening in A client of f...,A client of freshersworld,Posted: 1 months ago
15,Market Research Analyst Jobs Opening in ODN Di...,ODN Digital Services Private Limited,Posted: 6 days ago
16,Stock Market Research Analyst Jobs Opening in ...,Private Office,Posted: 1 months ago
17,Network Security Risk Analyst Jobs Opening in ...,A Client of Freshersworld,Posted: 9 days ago
18,IT Project Senior Analyst Jobs Opening in A Cl...,A Client of Freshersworld,Posted: 1 months ago
19,IT Project Senior Analyst Jobs Opening in A Cl...,A Client of Freshersworld,Posted: 1 months ago